Weather App Ready
rna/weather-app pull request #1
Opened 2020-09-03 18:43 UTC by rna

# Hello :hand: 

Implemented weather app with following features:
- Allows users to search for the weather of a specific location.
- Users can toggle between the Celcius and Fahrenheit degrees.
- User can view the images depending on the weather conditions.

[Live Preview](https://loving-jennings-1a1bce.netlify.app/)

2020-09-03 22:31 UTC, Forison requested changes
## Status:: Changes Required❌
# 🙋‍♂️ Ramesh
#### You have done a good job on this one so far, however, here are a few changes we have to make to get this project approved🤗.
* [x] There should be a toggle control to determine if the result will be shown in Celsius or Fahrenheit ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
* [ ] Let us use ES6 - object destructuring to get the values from an object. This way you can avoid repeating a lot of code. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/destructuring_requirement.png) from Pathwright)
Check my comment below👇

**[OPTIONAL]**

* [ ] Kindly make it a habit to always add a description to all the projects you create on Github.

#### Happy coding 👨‍💻
Addo Forison

2020-09-03 22:31 UTC, Forison commented on src/js/apiData.js
> +  cityName.innerHTML = data.name;
- You could destructure name, weather etc... from data to avoid repeating data.
```const {name,weather} = data```

2020-09-04 14:35 UTC, rna commented
# Hello 🙋‍♂️

### Implemented required changes.

Thanks.

2020-09-04 15:32 UTC, mosaaleb requested changes
#### Well done @rna :clap:

Thank you for handling the requirements from the previous review. Yet, all api request returns unauthorized because of the missing api key.

Please check my comment below.

Please fix issue, and submit a new code review.

##### Muhammad Ebeid

2020-09-04 15:32 UTC, mosaaleb commented on src/js/apiCall.js
> +  fetch(`https://api.openweathermap.org/data/2.5/weather?q=${place}&units=metric&APPID=${apiKey}`, { mode: 'cors' })
- [ ] All requests to openweather api return unauthorized response. Where is your apikey defined? I can't find the env file. Please make sure to include your api key in the project.

2020-09-04 15:49 UTC, rna commented on src/js/apiCall.js
> +  fetch(`https://api.openweathermap.org/data/2.5/weather?q=${place}&units=metric&APPID=${apiKey}`, { mode: 'cors' })
I don't understand why anyone will commit the sensitive keys to GitHub. It's not the best practice to do. If that is the case, what is the use of env method? If you want to view my project, you can view the live version.

2020-09-04 16:28 UTC, mosaaleb commented on src/js/apiCall.js
> +  fetch(`https://api.openweathermap.org/data/2.5/weather?q=${place}&units=metric&APPID=${apiKey}`, { mode: 'cors' })
Hi, 

![Screenshot from 2020-09-04 18-27-01](https://user-images.githubusercontent.com/4246637/92263064-52f19000-eedc-11ea-9bdc-2115b922386c.png)

Even if you haven't included it in your application, it will still be visible from the network tab in a browser console, the request is done from the client-side. If you want it completely hidden, check our this project [API-Key-Proxy-Server](https://github.com/MauricioRobayo/API-Key-Proxy-Server).

2020-09-04 16:31 UTC, mosaaleb approved these changes
#### Well done @rna :clap:

I have checked the app from the live link. It is working as expected :100: 

You can merge :+1:

2020-09-04 16:49 UTC, mosaaleb commented on src/js/apiCall.js
> +  fetch(`https://api.openweathermap.org/data/2.5/weather?q=${place}&units=metric&APPID=${apiKey}`, { mode: 'cors' })
Oh, sorry for the inconvenience. Thanks for clarification :+1:

2020-09-28 14:58 UTC, merged